# Generated by Django 5.1 on 2024-09-04 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('CertificacionId', models.AutoField(primary_key=True, serialize=False)),
                ('Certificacion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Certificacion',
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('ConceptoId', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Concepto',
            },
        ),
        migrations.CreateModel(
            name='CostosIndirectos',
            fields=[
                ('CostoId', models.AutoField(primary_key=True, serialize=False)),
                ('Costo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Costos_Indirectos',
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('GastoId', models.AutoField(primary_key=True, serialize=False)),
                ('Gasto', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Gastos',
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('LineaId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Linea',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('ModuloId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField(null=True, verbose_name='Descripcion')),
            ],
            options={
                'db_table': 'Modulo',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('PerfilId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('TipoDocumentoID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TipoDocumento',
            },
        ),
        migrations.CreateModel(
            name='DetalleCertificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentoId', models.CharField(max_length=50)),
                ('CertificacionId', models.CharField(max_length=50)),
                ('Fecha_Certificacion', models.DateField()),
            ],
            options={
                'db_table': 'Detalle_Certificacion',
                'unique_together': {('DocumentoId', 'CertificacionId')},
            },
        ),
        migrations.CreateModel(
            name='IND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anio', models.CharField(max_length=4)),
                ('Mes', models.CharField(max_length=2)),
                ('Indice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'IND',
                'unique_together': {('Anio', 'Mes')},
            },
        ),
        migrations.CreateModel(
            name='IPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anio', models.CharField(max_length=4)),
                ('Mes', models.CharField(max_length=2)),
                ('Indice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'IPC',
                'unique_together': {('Anio', 'Mes')},
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('ClienteId', models.AutoField(primary_key=True, serialize=False)),
                ('DocumentoId', models.CharField(max_length=20)),
                ('Nombre_Cliente', models.CharField(max_length=50)),
                ('Activo', models.BooleanField(default=True)),
                ('Fecha_Inicio', models.DateField()),
                ('Fecha_Retiro', models.DateField(blank=True, null=True)),
                ('TipoDocumentoID', models.ForeignKey(db_column='TipoDocumentoID', on_delete=django.db.models.deletion.CASCADE, to='Modulo.tipodocumento')),
            ],
            options={
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='TotalCostosIndirectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anio', models.CharField(max_length=4)),
                ('Mes', models.CharField(max_length=2)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'Total_Costos_Indirectos',
                'unique_together': {('Anio', 'Mes')},
            },
        ),
        migrations.CreateModel(
            name='TotalGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anio', models.CharField(max_length=4)),
                ('Mes', models.CharField(max_length=2)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'Total_Gastos',
                'unique_together': {('Anio', 'Mes')},
            },
        ),
        migrations.CreateModel(
            name='DetalleCostosIndirectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anio', models.CharField(max_length=4)),
                ('Mes', models.CharField(max_length=2)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CostosId', models.ForeignKey(db_column='CostosId', on_delete=django.db.models.deletion.CASCADE, to='Modulo.costosindirectos')),
            ],
            options={
                'db_table': 'Detalle_Costos_Indirectos',
                'unique_together': {('Anio', 'Mes', 'CostosId')},
            },
        ),
        migrations.CreateModel(
            name='DetalleGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anio', models.CharField(max_length=4)),
                ('Mes', models.CharField(max_length=2)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GastosId', models.ForeignKey(db_column='GastosId', on_delete=django.db.models.deletion.CASCADE, to='Modulo.gastos')),
            ],
            options={
                'db_table': 'Detalle_Gastos',
                'unique_together': {('Anio', 'Mes', 'GastosId')},
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anio', models.CharField(max_length=4)),
                ('Mes', models.CharField(max_length=2)),
                ('Documento', models.CharField(max_length=10)),
                ('Salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cliente', models.ForeignKey(db_column='ClienteId', on_delete=django.db.models.deletion.CASCADE, to='Modulo.clientes')),
            ],
            options={
                'db_table': 'Nomina',
                'unique_together': {('Anio', 'Mes', 'Documento')},
            },
        ),
        migrations.CreateModel(
            name='TiemposCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anio', models.CharField(max_length=4)),
                ('Mes', models.CharField(max_length=2)),
                ('Colaborador', models.CharField(max_length=100)),
                ('Horas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ClienteId', models.ForeignKey(db_column='ClienteId', on_delete=django.db.models.deletion.CASCADE, to='Modulo.clientes')),
            ],
            options={
                'db_table': 'Tiempos_Cliente',
                'unique_together': {('Anio', 'Mes', 'Colaborador', 'ClienteId')},
            },
        ),
        migrations.CreateModel(
            name='TiemposConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anio', models.CharField(max_length=4)),
                ('Mes', models.CharField(max_length=2)),
                ('Colaborador', models.CharField(max_length=100)),
                ('Horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ConceptoId', models.ForeignKey(db_column='ConceptoId', on_delete=django.db.models.deletion.CASCADE, to='Modulo.concepto')),
            ],
            options={
                'db_table': 'Tiempos_Concepto',
                'unique_together': {('Anio', 'Mes', 'Colaborador', 'ConceptoId')},
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Documento', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=100)),
                ('FechaNacimiento', models.DateField()),
                ('FechaIngreso', models.DateField()),
                ('FechaOperacion', models.DateField()),
                ('PerfilNombre', models.CharField(max_length=100)),
                ('Cargo', models.CharField(max_length=100)),
                ('TituloProfesional', models.CharField(max_length=100)),
                ('FechaGrado', models.DateField()),
                ('Universidad', models.CharField(max_length=100)),
                ('ProfesionRealizada', models.CharField(max_length=100)),
                ('TituloProfesionalActual', models.CharField(max_length=100)),
                ('UniversidadActual', models.CharField(max_length=100)),
                ('AcademiaSAP', models.CharField(max_length=100)),
                ('CertificadoSAP', models.CharField(max_length=100)),
                ('OtrasCertificaciones', models.TextField()),
                ('Postgrados', models.TextField()),
                ('LineaId', models.ForeignKey(db_column='LineaId', on_delete=django.db.models.deletion.CASCADE, to='Modulo.linea')),
                ('ModuloId', models.ForeignKey(db_column='ModuloId', on_delete=django.db.models.deletion.CASCADE, to='Modulo.modulo')),
                ('PerfilId', models.ForeignKey(db_column='PerfilId', on_delete=django.db.models.deletion.CASCADE, to='Modulo.perfil')),
                ('TipoDocumento', models.ForeignKey(db_column='TipoDocumento', on_delete=django.db.models.deletion.CASCADE, to='Modulo.tipodocumento')),
            ],
            options={
                'db_table': 'Empleado',
                'unique_together': {('TipoDocumento', 'Documento')},
            },
        ),
        migrations.CreateModel(
            name='Consultores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Documento', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=100)),
                ('Empresa', models.CharField(max_length=100)),
                ('Profesion', models.CharField(max_length=100)),
                ('Estado', models.BooleanField(default=True)),
                ('Fecha_Ingreso', models.DateField()),
                ('Fecha_Retiro', models.DateField(blank=True, null=True)),
                ('Direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('Fecha_Operacion', models.DateTimeField(auto_now=True)),
                ('LineaId', models.ForeignKey(db_column='LineaId', on_delete=django.db.models.deletion.CASCADE, to='Modulo.linea')),
                ('ModuloId', models.ForeignKey(db_column='ModuloId', on_delete=django.db.models.deletion.CASCADE, to='Modulo.modulo')),
                ('PerfilId', models.ForeignKey(db_column='PerfilId', on_delete=django.db.models.deletion.CASCADE, to='Modulo.perfil')),
                ('TipoDocumentoID', models.ForeignKey(db_column='TipoDocumentoID', on_delete=django.db.models.deletion.CASCADE, to='Modulo.tipodocumento')),
            ],
            options={
                'db_table': 'Consultores',
                'constraints': [models.UniqueConstraint(fields=('TipoDocumentoID', 'Documento'), name='unique_consultor')],
            },
        ),
        migrations.AddConstraint(
            model_name='clientes',
            constraint=models.UniqueConstraint(fields=('TipoDocumentoID', 'DocumentoId'), name='unique_cliente'),
        ),
    ]
