# Generated by Django 3.2.8 on 2024-08-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField(null=True, verbose_name='Descripcion')),
            ],
        ),
    ]
