# Generated by Django 3.2.8 on 2024-08-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modulo',
            table='Modulo',
        ),
    ]
