# Generated by Django 5.1.1 on 2024-09-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CostosIndirectos',
            new_name='Costos_Indirectos',
        ),
        migrations.RenameModel(
            old_name='DetalleCertificacion',
            new_name='Detalle_Certificacion',
        ),
        migrations.RenameModel(
            old_name='DetalleCostosIndirectos',
            new_name='Detalle_Costos_Indirectos',
        ),
        migrations.RenameModel(
            old_name='DetalleGastos',
            new_name='Detalle_Gastos',
        ),
        migrations.RenameModel(
            old_name='TiemposCliente',
            new_name='Tiempos_Cliente',
        ),
        migrations.RenameModel(
            old_name='TotalCostosIndirectos',
            new_name='Total_Costos_Indirectos',
        ),
        migrations.RenameModel(
            old_name='TotalGastos',
            new_name='Total_Gastos',
        ),
        migrations.AlterUniqueTogether(
            name='detalle_certificacion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='detalle_costos_indirectos',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='detalle_gastos',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ind',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ipc',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nomina',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tiempos_cliente',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tiemposconcepto',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='total_costos_indirectos',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='total_gastos',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='detalle_certificacion',
            constraint=models.UniqueConstraint(fields=('DocumentoId', 'CertificacionId'), name='unique_detalle_certificacion'),
        ),
        migrations.AddConstraint(
            model_name='detalle_costos_indirectos',
            constraint=models.UniqueConstraint(fields=('Anio', 'Mes', 'CostosId'), name='unique_detalle_costos_indirectos'),
        ),
        migrations.AddConstraint(
            model_name='detalle_gastos',
            constraint=models.UniqueConstraint(fields=('Anio', 'Mes', 'GastosId'), name='unique_detalle_gastos'),
        ),
        migrations.AddConstraint(
            model_name='ind',
            constraint=models.UniqueConstraint(fields=('Anio', 'Mes'), name='primary_key_IND'),
        ),
        migrations.AddConstraint(
            model_name='ipc',
            constraint=models.UniqueConstraint(fields=('Anio', 'Mes'), name='primary_key_IPC'),
        ),
        migrations.AddConstraint(
            model_name='nomina',
            constraint=models.UniqueConstraint(fields=('Anio', 'Mes', 'Documento'), name='unique_nomina'),
        ),
        migrations.AddConstraint(
            model_name='tiempos_cliente',
            constraint=models.UniqueConstraint(fields=('Anio', 'Mes', 'Colaborador', 'ClienteId'), name='unique_tiempos_cliente'),
        ),
        migrations.AddConstraint(
            model_name='tiemposconcepto',
            constraint=models.UniqueConstraint(fields=('Anio', 'Mes', 'Colaborador', 'ConceptoId'), name='unique_tiempos_concepto'),
        ),
        migrations.AddConstraint(
            model_name='total_costos_indirectos',
            constraint=models.UniqueConstraint(fields=('Anio', 'Mes'), name='unique_total_costos_indirectos'),
        ),
        migrations.AddConstraint(
            model_name='total_gastos',
            constraint=models.UniqueConstraint(fields=('Anio', 'Mes'), name='unique_total_gastos'),
        ),
    ]
