# Generated by Django 5.1 on 2024-08-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0002_alter_modulo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=4)),
                ('mes', models.CharField(max_length=2)),
                ('campo_numerico', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'IPC',
            },
        ),
    ]
