# Generated by Django 5.1.1 on 2024-09-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0002_rename_costosindirectos_costos_indirectos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='LineaId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
