# Generated by Django 5.1.1 on 2024-10-02 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0003_alter_linea_lineaid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linea',
            old_name='Nombre',
            new_name='Linea',
        ),
        migrations.RenameField(
            model_name='modulo',
            old_name='Nombre',
            new_name='Modulo',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='Nombre',
            new_name='Perfil',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='PerfilNombre',
        ),
        migrations.AlterField(
            model_name='detalle_certificacion',
            name='CertificacionId',
            field=models.ForeignKey(db_column='CertificacionId', on_delete=django.db.models.deletion.CASCADE, to='Modulo.certificacion'),
        ),
    ]
