# Generated by Django 5.1 on 2024-08-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0003_ipc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('ClienteId', models.AutoField(primary_key=True, serialize=False)),
                ('TipoDocumentoID', models.CharField(max_length=10)),
                ('DocumentoId', models.CharField(max_length=20)),
                ('Nombre_Cliente', models.CharField(max_length=50)),
                ('Activo', models.BooleanField(default=True)),
                ('Fecha_Inicio', models.DateField()),
                ('Fecha_Retiro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Clientes',
                'constraints': [models.UniqueConstraint(fields=('TipoDocumentoID', 'DocumentoId'), name='unique_cliente')],
            },
        ),
    ]
