# Generated by Django 3.2.8 on 2024-08-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0004_ind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'Linea',
            },
        ),
    ]
