# Generated by Django 5.1 on 2024-08-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0004_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultores',
            fields=[
                ('TipoDocumentoId', models.CharField(max_length=10)),
                ('Documento', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Empresa', models.CharField(max_length=100)),
                ('Profesion', models.CharField(max_length=100)),
                ('LineaId', models.CharField(max_length=50)),
                ('ModuloId', models.CharField(max_length=50)),
                ('Perfil', models.CharField(max_length=50)),
                ('Estado', models.BooleanField(default=True)),
                ('Fecha_Ingreso', models.DateField()),
                ('Fecha_Retiro', models.DateField(blank=True, null=True)),
                ('Direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('Fecha_Operacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Consultores',
                'constraints': [models.UniqueConstraint(fields=('TipoDocumentoId', 'Documento'), name='unique_consultor')],
            },
        ),
    ]
