# Generated by Django 5.1.1 on 2024-10-08 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0004_rename_nombre_linea_linea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='Documento',
            field=models.ForeignKey(db_column='Empleado', on_delete=django.db.models.deletion.CASCADE, to='Modulo.empleado'),
        ),
    ]
