# Generated by Django 3.2.8 on 2024-08-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0005_linea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
    ]
