# Generated by Django 5.1.1 on 2024-10-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0005_alter_nomina_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='Documento',
            field=models.CharField(max_length=10),
        ),
    ]
