# Generated by Django 5.1.1 on 2024-12-04 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0006_alter_nomina_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('CargoId', models.AutoField(primary_key=True, serialize=False)),
                ('Cargo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Cargos',
            },
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='Cargo',
        ),
        migrations.AddField(
            model_name='empleado',
            name='CargoId',
            field=models.ForeignKey(db_column='CargoId', default=1, on_delete=django.db.models.deletion.CASCADE, to='Modulo.cargos'),
            preserve_default=False,
        ),
    ]
