# Generated by Django 5.1 on 2024-08-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0005_consultores'),
        ('Modulo', '0007_auto_20240820_2334'),
    ]

    operations = [
    ]
